kind: Service
apiVersion: v1
metadata:
  name: chisharma-org
  labels:
    net.beedemo.deploy.type: workshop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: chisharma-org
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chisharma-org-staging
  labels:
    net.beedemo.deploy.type: workshop
spec:
  replicas: 1
  template:
    metadata:
      name: chisharma-org
      labels:
        net.beedemo.deploy.type: workshop
        app: chisharma-org
        env: staging
    spec:
      containers:
      - name: chisharma-org
        image: gcr.io/core-workshop/helloworld-nodejs:chisharma-org-6
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chisharma-org
  labels:
    net.beedemo.deploy.type: workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /chisharma-org/?(.*)
        backend:
          serviceName: chisharma-org
          servicePort: 80
    host: staging.cb-sa.io
